name: "171_304 to 193 (Fast-DDPM)"

data:
  ext: npy
  image_size: 1024
  train:
    input_dir: /userhome/jeon_mg/workspace/aia_dataset/train/input
    target_dir: /userhome/jeon_mg/workspace/aia_dataset/train/target
    batch_size: 2
    shuffle: true
    num_workers: 4
    pin_memory: true
    drop_last: true
  val:
    input_dir: /userhome/jeon_mg/workspace/aia_dataset/val/input
    target_dir: /userhome/jeon_mg/workspace/aia_dataset/val/target
    batch_size: 1
    shuffle: false
    num_workers: 0
    pin_memory: false
    drop_last: false
  test:
    input_dir: /userhome/jeon_mg/workspace/aia_dataset/test/input
    target_dir: /userhome/jeon_mg/workspace/aia_dataset/test/target
    batch_size: 1
    shuffle: false
    num_workers: 0
    pin_memory: false
    drop_last: false

model:
  name: ddim_unet
  args:
    input_nc: 3     # channel of input image (condition)
    output_nc: 1    # channel of target image = channel of noise
    ch: 128
    ch_mult: [1, 1, 1, 2, 2, 2, 4, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    resamp_with_conv: True
    resolution: 1024

params:
  model:
    ema: True
    ema_rate: 0.999
  diffusion:  
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_timesteps: 1000
    fast_ddpm: True
  sampling:
    fixed_initial_noise: True
    eta: 0.0
    timesteps: 10        # skip = num_time_steps // timesteps
    # beta_schedule_type: "uniform"                            Fast-DDPM
  optimizer:
    name: Adam
    args:
      lr: 0.00001
      betas: [0.5, 0.999]
  # grad_clip:
  #   clip: True
  #   max_norm: 1.0
  loss:
    name: MSELoss
    args:
      reduction: sum
      average_over_batch: True
  num_epochs: 50
  log_per_iteration: 50
  save_img_per_epoch: 1
  save_state_per_epoch: 1
  save_top_k: -1
  seed: 42
  float32_matmul_precision: "high"
  accelerator: "cuda"
  devices: [3]
  precision: "32-true"
  strategy: "ddp"
  output_dir: /userhome/jeon_mg/workspace/results/sdo/diffusion/fast_ddpm
  resume_from: null