data:
  ext: jpg
  image_size: 256
  train:
    input_dir: ../datasets/facades/train/A
    target_dir: ../datasets/facades/train/B
    batch_size: 4
    shuffle: true
    num_workers: 4
    pin_memory: true
    drop_last: true
  val:
    input_dir: ../datasets/facades/val/A
    target_dir: ../datasets/facades/val/B
    batch_size: 1
    shuffle: false
    num_workers: 0
    pin_memory: true
    drop_last: false
  test:
    input_dir: ../datasets/facades/test/A
    target_dir: ../datasets/facades/test/B
    batch_size: 1
    shuffle: false
    num_workers: 0
    pin_memory: true
    drop_last: false
model:
  generator:
    name: simple_G
    args:
      in_channels: 3
      out_channels: 3
      features: 64
  discriminator:
    name: simple_D
    args:
      in_channels: 6
      features: [64, 128, 256, 512]
params:
  optimizer:
    name: Adam
    args:
      lr: 0.0002
      betas: [0.5, 0.999]
  loss:
    generator:
      name: L1Loss
      lambda: 100
    discriminator:
      name: BCEWithLogitsLoss
  num_epochs: 100
  log_per_iteration: 10
  save_img_per_epoch: 1
  save_state_per_epoch: 50
  seed: 42
  float32_matmul_precision: "high"
  accelerator: "cuda"
  devices: '0'
  output_dir: ./results/default
  resume_from: null