data:
  ext: npy
  image_size: 256
  train:
    input_dir: /userhome/jeon_mg/workspace/aia_dataset_256/train/input
    target_dir: /userhome/jeon_mg/workspace/aia_dataset_256/train/target
    batch_size: 8
    shuffle: true
    num_workers: 4
    pin_memory: true
    drop_last: true
  val:
    input_dir: /userhome/jeon_mg/workspace/aia_dataset_256/val/input
    target_dir: /userhome/jeon_mg/workspace/aia_dataset_256/val/target
    batch_size: 1
    shuffle: false
    num_workers: 0
    pin_memory: false
    drop_last: false
  test:
    input_dir: /userhome/jeon_mg/workspace/aia_dataset_256/test/input
    target_dir: /userhome/jeon_mg/workspace/aia_dataset_256/test/target
    batch_size: 1
    shuffle: false
    num_workers: 0
    pin_memory: false
    drop_last: false
model:
  generator:
    name: unet
    args:
      input_nc: 2
      output_nc: 1
      num_downs: 8
      ngf: 64
      norm_layer: instance
      use_dropout: false
      init_type: normal
      init_gain: 0.02
  discriminator:
    name: patchgan
    args:
      input_nc: 3
      ndf: 64
      n_layers: 3
      norm_layer: instance
      init_type: normal
      init_gain: 0.02
params:
  optimizer:
    name: Adam
    args:
      lr: 0.0002
      betas: [0.5, 0.999]
  loss:
    adversarial:
      name: BCEWithLogitsLoss
      args: null
    reconstruction:
      name: L1Loss
      args:
        lambdaL1: 100
  num_epochs: 3
  log_per_iteration: 50
  save_img_per_epoch: 1
  save_state_per_epoch: 1
  save_top_k: -1
  seed: 42
  float32_matmul_precision: "high"
  accelerator: "cuda"
  devices: [2,3]
  precision: "32-true"
  strategy: "ddp"
  output_dir: ./results/sdo/unet_patchgan
  resume_from: null